//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_CO_JOBCTRL
    {
        public string RECID { get; set; }
        public string PROCESSID { get; set; }
        public string SUBPROCESSID { get; set; }
        public Nullable<int> RUNMODE { get; set; }
        public string RUNID { get; set; }
        public int JOBSTATUS { get; set; }
        public System.DateTime STARTDATETIME { get; set; }
        public Nullable<System.DateTime> ENDDATETIME { get; set; }
        public string REMARKS { get; set; }
        public string CREATEUSERID { get; set; }
        public System.DateTime CREATEDATETIME { get; set; }
        public string CHANGEUSERID { get; set; }
        public Nullable<System.DateTime> CHANGEDATETIME { get; set; }
        public string JOBSTREAM { get; set; }
        public string EXCLRESOURCE { get; set; }
    }
}
