//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_CO_FILECONTROL
    {
        public string RECID { get; set; }
        public string PROCESSID { get; set; }
        public string RUNID { get; set; }
        public string SUBPROCESS { get; set; }
        public Nullable<int> ISREPROCESS { get; set; }
        public string FILENAME { get; set; }
        public string STARTSEQNO { get; set; }
        public string ENDSEQNO { get; set; }
        public Nullable<System.DateTime> PROCESSDATETIME { get; set; }
        public string OUTPUTFILENAME { get; set; }
        public Nullable<int> NOFINPUT { get; set; }
        public Nullable<int> NOFVALID { get; set; }
        public Nullable<int> NOFREJECT { get; set; }
        public Nullable<int> NOFIGNORE { get; set; }
        public Nullable<int> DELETEIND { get; set; }
    }
}
