//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ls_logtableresult
    {
        public string tablename { get; set; }
        public string jobname { get; set; }
        public Nullable<System.DateTime> thedatetime { get; set; }
        public string theday { get; set; }
        public Nullable<int> logdata { get; set; }
        public Nullable<int> tabledata { get; set; }
        public Nullable<System.DateTime> lastupdatedate { get; set; }
    }
}
