//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPlusEntities : DbContext
    {
        public SPlusEntities()
            : base("name=SPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<web_jobtable> web_jobtable { get; set; }
        public virtual DbSet<FW_CO_FILECONTROL> FW_CO_FILECONTROL { get; set; }
        public virtual DbSet<FW_CO_JOBCTRL> FW_CO_JOBCTRL { get; set; }
    }
}
