CREATE TABLE  #ORDERS(ID VARCHAR(10),NAME VARCHAR(10),NOTE VARCHAR(10),PRODUCTID VARCHAR(10),CUSTOMERID VARCHAR(10))
CREATE TABLE  #PRODUCT(ID VARCHAR(10),PDODUCTNAME nVARCHAR(20))
CREATE TABLE  #CUSTOMER(ID VARCHAR(10),CUSTOMERNAME nVARCHAR(20))

drop table #PRODUCT
drop table  #ORDERS
drop table  #CUSTOMER


INSERT INTO #ORDERS(ID,NAME,NOTE,PRODUCTID,CUSTOMERID) SELECT '1','0001','CI1','1','1'
INSERT INTO #ORDERS(ID,NAME,NOTE,PRODUCTID,CUSTOMERID) SELECT'2','0002','CI2','1','2'
INSERT INTO #ORDERS (ID,NAME,NOTE,PRODUCTID,CUSTOMERID)SELECT'3','0003','CI3','1','3'
INSERT INTO #ORDERS(ID,NAME,NOTE,PRODUCTID,CUSTOMERID) SELECT'4','0004','CI4','1','4'
INSERT INTO #ORDERS(ID,NAME,NOTE,PRODUCTID,CUSTOMERID) SELECT '5','0005','CI4','2','2'

INSERT INTO #PRODUCT(ID,PDODUCTNAME) SELECT '1','apple'
INSERT INTO #PRODUCT(ID,PDODUCTNAME) SELECT '2','banan'
INSERT INTO #PRODUCT(ID,PDODUCTNAME) SELECT '3','juzi'
INSERT INTO #PRODUCT(ID,PDODUCTNAME) SELECT '4','jirou'


INSERT INTO #CUSTOMER(ID,CUSTOMERNAME) SELECT '1','goou'
INSERT INTO #CUSTOMER(ID,CUSTOMERNAME) SELECT '2','ren'
INSERT INTO #CUSTOMER(ID,CUSTOMERNAME) SELECT '3','zhansan'
INSERT INTO #CUSTOMER(ID,CUSTOMERNAME) SELECT '4','wangwu'

cross 
select a.*,'---',b.* from 
#ORDERS a cross join #PRODUCT b  where  a.PRODUCTID=b.ID

left 



select a.*,'---',b.* from 
#ORDERS a left join #PRODUCT b  on  a.PRODUCTID=b.ID -- and a.CUSTOMERID=2

select a.*,'---',b.* from 
#ORDERS a left join #PRODUCT b  on  a.PRODUCTID=b.ID and a.CUSTOMERID=2

select a.*,'---',b.* from 
#ORDERS a left join #PRODUCT b  on  a.PRODUCTID=b.ID and b.ID=2

select * from #ORDERS
select * from #PRODUCT



